/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogItemRouteImport } from './routes/catalog.$item'
import { Route as InquiriesIndexRouteImport } from './routes/inquiries.index'
import { Route as InquiriesIdRouteImport } from './routes/inquiries.$id'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogItemRoute = CatalogItemRouteImport.update({
  id: '/catalog/$item',
  path: '/catalog/$item',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesIndexRoute = InquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesIdRoute = InquiriesIdRouteImport.update({
  id: '/inquiries/$id',
  path: '/inquiries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/catalog/$item': typeof CatalogItemRoute
  '/inquiries/$id': typeof InquiriesIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/catalog/': typeof CatalogIndexRoute
  '/inquiries/': typeof InquiriesIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/catalog/$item': typeof CatalogItemRoute
  '/inquiries/$id': typeof InquiriesIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/catalog': typeof CatalogIndexRoute
  '/inquiries': typeof InquiriesIndexRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/catalog/$item': typeof CatalogItemRoute
  '/inquiries/$id': typeof InquiriesIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/catalog/': typeof CatalogIndexRoute
  '/inquiries/': typeof InquiriesIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/catalog/$item'
    | '/inquiries/$id'
    | '/orders/$id'
    | '/catalog/'
    | '/inquiries/'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/catalog/$item'
    | '/inquiries/$id'
    | '/orders/$id'
    | '/catalog'
    | '/inquiries'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/catalog/$item'
    | '/inquiries/$id'
    | '/orders/$id'
    | '/catalog/'
    | '/inquiries/'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  CatalogItemRoute: typeof CatalogItemRoute
  InquiriesIdRoute: typeof InquiriesIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  InquiriesIndexRoute: typeof InquiriesIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$item': {
      id: '/catalog/$item'
      path: '/catalog/$item'
      fullPath: '/catalog/$item'
      preLoaderRoute: typeof CatalogItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries/': {
      id: '/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof InquiriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries/$id': {
      id: '/inquiries/$id'
      path: '/inquiries/$id'
      fullPath: '/inquiries/$id'
      preLoaderRoute: typeof InquiriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  CatalogItemRoute: CatalogItemRoute,
  InquiriesIdRoute: InquiriesIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  InquiriesIndexRoute: InquiriesIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
